FROM golang:1.22-alpine AS builder
WORKDIR /build

COPY go.* ./

RUN go mod download && go mod tidy

COPY . .

RUN go build -o /medods-app ./main.go

FROM alpine:3
WORKDIR /app

COPY --from=builder /medods-app ./main

EXPOSE 8042
VOLUME ["/config"]

ENTRYPOINT ["./main"]