
services: 
  db:
    hostname: medods-db
    image: postgres:16.1
    restart: always
    env_file:
      - path: ./config/.env
        required: true
    ports:
      - "3001:5432"

  medods:
    build:
      context: .
    restart: always
    hostname: medods
    depends_on:
      - db
    env_file:
      - ./config/.env
    environment:
      POSTGRES_HOST: medods-db
    volumes:
      - ./config:/config  